baseURL = 'https://kylejones200.github.io/ml4u/'
languageCode = 'en-us'
title = 'Machine Learning for Power & Utilities'
cleanDestinationDir = true

# Pagination
[pagination]
  pagerSize = 10
enableRobotsTXT = true

# Enable raw HTML in Markdown (Goldmark)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Disable kinds we don't use
disableKinds = ["RSS", "taxonomy", "term"]

# Force outputs for home to include HTML (prevents feed-only home)
[outputs]
  home = ["HTML"]

# Disable taxonomies
[taxonomies]
