baseURL = 'https://kylejones200.github.io/ml4u/'
languageCode = 'en-us'
title = 'Machine Learning for Power & Utilities'
theme = 'blowfish'

# Pagination
[pagination]
  pagerSize = 10
enableRobotsTXT = true

# Enable raw HTML in Markdown (Goldmark)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
